### PR TITLE
[Operator] Add diag_embed

### LINKED ISSUE #253: Code Contribution: 【Lv1】【Operator Development】diag_embed
将以下算子贡献至https://github.com/FlagOpen/FlagGems/tree/master/src/flag_gems/ops 目录下

diag_embed

认领方式：
1. Issue中留言评论：「认领人名称+认领」
2. 在贡献者微信群内发送：认领的Issue号例如：「认领+[https://github.com/FlagOpen/FlagGems/issues/xxx]」

### PR DESCRIPTION
**Pull request by 2niuhe**
### PR Category

Operator

### Type of Change

New Feature

### Description

Implement diag_embed operator

### Issue

- Resolves #253 

### Progress

- [ ] Change is properly reviewed (1 reviewer required, 2 recommended).
- [ ] Change is responded to an issue.
- [ ] Change is fully covered by a UT.

### Performance

Test on A100

 
- CORE

```
Operator: diag_embed  Performance Test (dtype=torch.float16, mode=cuda, level=core)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.011264            0.014336               0.786          {'input': torch.Size([4, 4])}
N/A                   0.011264            0.015360               0.733          {'input': torch.Size([16, 16])}
N/A                   0.015360            0.016384               0.937          {'input': torch.Size([128, 128])}
N/A                   0.037888            0.033792               1.121          {'input': torch.Size([256, 256])}
N/A                   1.743872            1.573888               1.108          {'input': torch.Size([1024, 1024])}


Operator: diag_embed  Performance Test (dtype=torch.float32, mode=cuda, level=core)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.015360               0.600          {'input': torch.Size([4, 4])}
N/A                   0.010240            0.015360               0.667          {'input': torch.Size([16, 16])}
N/A                   0.016384            0.015360               1.067          {'input': torch.Size([128, 128])}
N/A                   0.058368            0.057344               1.018          {'input': torch.Size([256, 256])}
N/A                   2.961408            2.957312               1.001          {'input': torch.Size([1024, 1024])}


Operator: diag_embed  Performance Test (dtype=torch.bfloat16, mode=cuda, level=core)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.013312               0.692          {'input': torch.Size([4, 4])}
N/A                   0.009216            0.012288               0.750          {'input': torch.Size([16, 16])}
N/A                   0.015360            0.015360               1.000          {'input': torch.Size([128, 128])}
N/A                   0.037888            0.033792               1.121          {'input': torch.Size([256, 256])}
N/A                   1.743872            1.573888               1.108          {'input': torch.Size([1024, 1024])}


Operator: diag_embed  Performance Test (dtype=torch.int16, mode=cuda, level=core)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.014336               0.643          {'input': torch.Size([4, 4])}
N/A                   0.009216            0.018432               0.500          {'input': torch.Size([16, 16])}
N/A                   0.015360            0.016384               0.937          {'input': torch.Size([128, 128])}
N/A                   0.037888            0.033792               1.121          {'input': torch.Size([256, 256])}
N/A                   1.743872            1.573888               1.108          {'input': torch.Size([1024, 1024])}


Operator: diag_embed  Performance Test (dtype=torch.int32, mode=cuda, level=core)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.018432               0.500          {'input': torch.Size([4, 4])}
N/A                   0.010240            0.015360               0.667          {'input': torch.Size([16, 16])}
N/A                   0.016384            0.019456               0.842          {'input': torch.Size([128, 128])}
N/A                   0.058368            0.057344               1.018          {'input': torch.Size([256, 256])}
N/A                   2.960384            2.957312               1.001          {'input': torch.Size([1024, 1024])}


Operator: diag_embed  Performance Test (dtype=torch.bool, mode=cuda, level=core)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.015360               0.600          {'input': torch.Size([4, 4])}
N/A                   0.009216            0.028672               0.321          {'input': torch.Size([16, 16])}
N/A                   0.015360            0.017408               0.882          {'input': torch.Size([128, 128])}
N/A                   0.036864            0.023552               1.565          {'input': torch.Size([256, 256])}
N/A                   1.740800            0.962560               1.809          {'input': torch.Size([1024, 1024])}
```

- COMPREHENSIVE

```
Operator: diag_embed  Performance Test (dtype=torch.float16, mode=cuda, level=comprehensive)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.011264            0.017408               0.647          {'input': torch.Size([4, 4])}
N/A                   0.009216            0.015360               0.600          {'input': torch.Size([4, 4]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.009216            0.020480               0.450          {'input': torch.Size([16, 16])}
N/A                   0.009216            0.021504               0.429          {'input': torch.Size([16, 16]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.015360            0.048128               0.319          {'input': torch.Size([128, 128])}
N/A                   0.014336            0.021504               0.667          {'input': torch.Size([128, 128]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.038912            0.033792               1.152          {'input': torch.Size([256, 256])}
N/A                   0.037888            0.034816               1.088          {'input': torch.Size([256, 256]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   1.745920            1.573888               1.109          {'input': torch.Size([1024, 1024])}
N/A                   1.755136            1.580032               1.111          {'input': torch.Size([1024, 1024]), 'offset': 1, 'dim1': 0, 'dim2': -1}


Operator: diag_embed  Performance Test (dtype=torch.float32, mode=cuda, level=comprehensive)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.038912               0.237          {'input': torch.Size([4, 4])}
N/A                   0.009216            0.018432               0.500          {'input': torch.Size([4, 4]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.009216            0.022528               0.409          {'input': torch.Size([16, 16])}
N/A                   0.009216            0.018432               0.500          {'input': torch.Size([16, 16]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.016384            0.019456               0.842          {'input': torch.Size([128, 128])}
N/A                   0.015360            0.019456               0.789          {'input': torch.Size([128, 128]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.058368            0.057344               1.018          {'input': torch.Size([256, 256])}
N/A                   0.059392            0.058368               1.018          {'input': torch.Size([256, 256]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   2.961408            2.958336               1.001          {'input': torch.Size([1024, 1024])}
N/A                   2.975744            2.960384               1.005          {'input': torch.Size([1024, 1024]), 'offset': 1, 'dim1': 0, 'dim2': -1}


Operator: diag_embed  Performance Test (dtype=torch.bfloat16, mode=cuda, level=comprehensive)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.019456               0.474          {'input': torch.Size([4, 4])}
N/A                   0.009216            0.023552               0.391          {'input': torch.Size([4, 4]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.009216            0.016384               0.563          {'input': torch.Size([16, 16])}
N/A                   0.009216            0.017408               0.529          {'input': torch.Size([16, 16]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.015360            0.019456               0.789          {'input': torch.Size([128, 128])}
N/A                   0.014336            0.022528               0.636          {'input': torch.Size([128, 128]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.038912            0.033792               1.152          {'input': torch.Size([256, 256])}
N/A                   0.037888            0.034816               1.088          {'input': torch.Size([256, 256]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   1.744896            1.573888               1.109          {'input': torch.Size([1024, 1024])}
N/A                   1.755136            1.579008               1.112          {'input': torch.Size([1024, 1024]), 'offset': 1, 'dim1': 0, 'dim2': -1}


Operator: diag_embed  Performance Test (dtype=torch.int16, mode=cuda, level=comprehensive)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.015360               0.600          {'input': torch.Size([4, 4])}
N/A                   0.009216            0.048128               0.191          {'input': torch.Size([4, 4]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.009216            0.020480               0.450          {'input': torch.Size([16, 16])}
N/A                   0.009216            0.020480               0.450          {'input': torch.Size([16, 16]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.015360            0.024576               0.625          {'input': torch.Size([128, 128])}
N/A                   0.014336            0.025600               0.560          {'input': torch.Size([128, 128]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.038912            0.033792               1.152          {'input': torch.Size([256, 256])}
N/A                   0.037888            0.034816               1.088          {'input': torch.Size([256, 256]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   1.743872            1.573888               1.108          {'input': torch.Size([1024, 1024])}
N/A                   1.755136            1.579008               1.112          {'input': torch.Size([1024, 1024]), 'offset': 1, 'dim1': 0, 'dim2': -1}


Operator: diag_embed  Performance Test (dtype=torch.int32, mode=cuda, level=comprehensive)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.025600               0.360          {'input': torch.Size([4, 4])}
N/A                   0.009216            0.018432               0.500          {'input': torch.Size([4, 4]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.009216            0.049152               0.188          {'input': torch.Size([16, 16])}
N/A                   0.009216            0.032768               0.281          {'input': torch.Size([16, 16]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.016384            0.025600               0.640          {'input': torch.Size([128, 128])}
N/A                   0.015360            0.022528               0.682          {'input': torch.Size([128, 128]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.058368            0.057344               1.018          {'input': torch.Size([256, 256])}
N/A                   0.059392            0.058368               1.018          {'input': torch.Size([256, 256]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   2.961408            2.957312               1.001          {'input': torch.Size([1024, 1024])}
N/A                   2.975744            2.961408               1.005          {'input': torch.Size([1024, 1024]), 'offset': 1, 'dim1': 0, 'dim2': -1}


Operator: diag_embed  Performance Test (dtype=torch.bool, mode=cuda, level=comprehensive)
Size         Torch Latency (ms)    Gems Latency (ms)         Gems Speedup         Size Detail
------------------------------------------------------------------------------------------
N/A                   0.009216            0.020480               0.450          {'input': torch.Size([4, 4])}
N/A                   0.009216            0.019456               0.474          {'input': torch.Size([4, 4]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.009216            0.020480               0.450          {'input': torch.Size([16, 16])}
N/A                   0.009216            0.023552               0.391          {'input': torch.Size([16, 16]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.015360            0.022528               0.682          {'input': torch.Size([128, 128])}
N/A                   0.014336            0.020480               0.700          {'input': torch.Size([128, 128]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   0.037888            0.023552               1.609          {'input': torch.Size([256, 256])}
N/A                   0.036864            0.025600               1.440          {'input': torch.Size([256, 256]), 'offset': 1, 'dim1': 0, 'dim2': -1}
N/A                   1.740800            0.962560               1.809          {'input': torch.Size([1024, 1024])}
N/A                   1.748992            0.966656               1.809          {'input': torch.Size([1024, 1024]), 'offset': 1, 'dim1': 0, 'dim2': -1}
```

### CODE REVIEW

**Review by Galaxy1458 — DISMISSED** [review]

**Comment by 2niuhe** [comment]
@Galaxy1458  I have resolved the merge conflicts. Please review and merge the PR again.

**Comment by 2niuhe** [comment]
@Tango2018cc @Galaxy1458 pr needs review

**Comment by Galaxy1458** [comment]
> @Tango2018cc @Galaxy1458 pr needs review

Thank you for your contribution！ but please implement the algorithm in Triton's kernel using tl primitives instead of copy_func(x).

**Comment by 2niuhe** [comment]
@Galaxy1458 

Thank you for your feedback! I appreciate your suggestion to implement the algorithm using Triton's kernel with `tl` primitives instead of `copy_func(x)`. 

However, I want to clarify that in the PyTorch implementation of `diag_embed`, the only GPU kernel operation is the `copy_`, while the rest involves tensor metadata calculations. I did attempt to implement it using pure Triton, but ultimately found that mimicking the simplicity of the PyTorch approach was more effective.

Here's the relevant PyTorch implementation for your reference:

`aten/src/ATen/native/TensorShape.cpp`

```cpp
Tensor diag_embed(const Tensor& self, int64_t offset, int64_t dim1_, int64_t dim2_) {
  int64_t nDims = self.dim() + 1;
  int64_t dim1 = maybe_wrap_dim(dim1_, nDims);
  int64_t dim2 = maybe_wrap_dim(dim2_, nDims);
  TORCH_CHECK(dim1 != dim2, "diagonal dimensions cannot be identical ", dim1_, ", ", dim2_);
  int64_t new_dim_len = std::abs(offset) + self.size(-1);
  auto sizes = self.sizes().vec();
  sizes.pop_back();
  sizes.insert(sizes.begin() + std::min(dim1, dim2), new_dim_len);
  sizes.insert(sizes.begin() + std::max(dim1, dim2), new_dim_len);
  auto result = at::zeros(sizes, self.options());
  auto diag = result.diagonal(offset, dim1, dim2);
  diag.copy_(self);
  return result;
}
```

I also drew inspiration from several other operator implementations that utilize `copy_func`, including:

```
(venv) ➜  FlagGems git:(master) ✗ grep "def copy_func" -r ./
./src/flag_gems/ops/stack.py:def copy_func(x):
./src/flag_gems/ops/flip.py:def copy_func(x):
./src/flag_gems/ops/repeat_interleave.py:def copy_func(x):
./src/flag_gems/ops/cat.py:def copy_func(x):
./src/flag_gems/ops/hstack.py:def copy_func(x):
```

**Could you please reconsider the use of `copy_func` in this context? If you have any alternative suggestions, I would be open to exploring them, as I am still getting familiar with Triton programming.**

Thanks again for your understanding!

**Comment by Galaxy1458** [comment]
> @Galaxy1458
> 
> Thank you for your feedback! I appreciate your suggestion to implement the algorithm using Triton's kernel with `tl` primitives instead of `copy_func(x)`.
> 
> However, I want to clarify that in the PyTorch implementation of `diag_embed`, the only GPU kernel operation is the `copy_`, while the rest involves tensor metadata calculations. I did attempt to implement it using pure Triton, but ultimately found that mimicking the simplicity of the PyTorch approach was more effective.
> 
> Here's the relevant PyTorch implementation for your reference:
> 
> `aten/src/ATen/native/TensorShape.cpp`
> 
> ```c++
> Tensor diag_embed(const Tensor& self, int64_t offset, int64_t dim1_, int64_t dim2_) {
>   int64_t nDims = self.dim() + 1;
>   int64_t dim1 = maybe_wrap_dim(dim1_, nDims);
>   int64_t dim2 = maybe_wrap_dim(dim2_, nDims);
>   TORCH_CHECK(dim1 != dim2, "diagonal dimensions cannot be identical ", dim1_, ", ", dim2_);
>   int64_t new_dim_len = std::abs(offset) + self.size(-1);
>   auto sizes = self.sizes().vec();
>   sizes.pop_back();
>   sizes.insert(sizes.begin() + std::min(dim1, dim2), new_dim_len);
>   sizes.insert(sizes.begin() + std::max(dim1, dim2), new_dim_len);
>   auto result = at::zeros(sizes, self.options());
>   auto diag = result.diagonal(offset, dim1, dim2);
>   diag.copy_(self);
>   return result;
> }
> ```
> 
> I also drew inspiration from several other operator implementations that utilize `copy_func`, including:
> 
> ```
> (venv) ➜  FlagGems git:(master) ✗ grep "def copy_func" -r ./
> ./src/flag_gems/ops/stack.py:def copy_func(x):
> ./src/flag_gems/ops/flip.py:def copy_func(x):
> ./src/flag_gems/ops/repeat_interleave.py:def copy_func(x):
> ./src/flag_gems/ops/cat.py:def copy_func(x):
> ./src/flag_gems/ops/hstack.py:def copy_func(x):
> ```
> 
> **Could you please reconsider the use of `copy_func` in this context? If you have any alternative suggestions, I would be open to exploring them, as I am still getting familiar with Triton programming.**
> 
> Thanks again for your understanding!

**Review by Galaxy1458 — COMMENTED** [review]
After our team discussion, we think that this PR can be integrated. Thank you very much for your contribution！

**Review by Galaxy1458 — APPROVED** [review]

**Pull request merged**
